// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallMap(arg1, arg2) {
  return window['go']['downloader']['Downloader']['InstallMap'](arg1, arg2);
}

export function InstallMod(arg1, arg2) {
  return window['go']['downloader']['Downloader']['InstallMod'](arg1, arg2);
}

export function UninstallMap(arg1) {
  return window['go']['downloader']['Downloader']['UninstallMap'](arg1);
}

export function UninstallMod(arg1) {
  return window['go']['downloader']['Downloader']['UninstallMod'](arg1);
}
