// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['config']['Config']['ClearConfig']();
}

export function GetConfig() {
  return window['go']['config']['Config']['GetConfig']();
}

export function OpenExecutableDialog(arg1) {
  return window['go']['config']['Config']['OpenExecutableDialog'](arg1);
}

export function OpenMetroMakerDataFolderDialog(arg1) {
  return window['go']['config']['Config']['OpenMetroMakerDataFolderDialog'](arg1);
}

export function ResolveConfig() {
  return window['go']['config']['Config']['ResolveConfig']();
}

export function SaveConfig() {
  return window['go']['config']['Config']['SaveConfig']();
}

export function SetConfig(arg1) {
  return window['go']['config']['Config']['SetConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['config']['Config']['SetContext'](arg1);
}

export function TryAutoDetectPath(arg1, arg2, arg3, arg4) {
  return window['go']['config']['Config']['TryAutoDetectPath'](arg1, arg2, arg3, arg4);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['config']['Config']['UpdateConfig'](arg1, arg2);
}

export function UpdateExecutable(arg1) {
  return window['go']['config']['Config']['UpdateExecutable'](arg1);
}

export function UpdateMetroMakerDataFolder(arg1) {
  return window['go']['config']['Config']['UpdateMetroMakerDataFolder'](arg1);
}
