// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateProfileArchive(arg1:string):Promise<types.GenericResponse>;

export function GetActiveProfile():Promise<types.UserProfileResult>;

export function LoadProfiles():Promise<types.UserProfileResult>;

export function QuarantineUserProfiles():Promise<boolean|string>;

export function ResetUserProfiles():Promise<types.UserProfileResult>;

export function RestoreProfileArchive(arg1:string):Promise<types.GenericResponse>;

export function SyncSubscriptions(arg1:string):Promise<types.SyncSubscriptionsResult>;

export function UpdateSubscriptions(arg1:types.UpdateSubscriptionsRequest):Promise<types.UpdateSubscriptionsResult>;

export function UpdateSubscriptionsToLatest(arg1:types.UpdateSubscriptionsToLatestRequest):Promise<types.UpdateSubscriptionsResult>;

export function UpdateSystemPreferences(arg1:types.SystemPreferences):Promise<types.UserProfileResult>;

export function UpdateUIPreferences(arg1:types.UIPreferences):Promise<types.UserProfileResult>;
