// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateProfile(arg1:types.CreateProfileRequest):Promise<types.UserProfileResult>;

export function CreateProfileArchive(arg1:string):Promise<types.GenericResponse>;

export function DeleteProfile(arg1:string):Promise<types.UserProfileResult>;

export function GetActiveProfile():Promise<types.UserProfileResult>;

export function ImportAsset(arg1:types.ImportAssetRequest):Promise<types.UpdateSubscriptionsResult>;

export function ListProfiles():Promise<types.UserProfilesListResult>;

export function LoadProfiles():Promise<types.UserProfileResult>;

export function QuarantineUserProfiles():Promise<boolean|string>;

export function ReconcileLocalMapSubscriptions(arg1:string):Promise<types.UpdateSubscriptionsResult>;

export function RenameProfile(arg1:string,arg2:string):Promise<types.UserProfileResult>;

export function ResetUserProfiles():Promise<types.UserProfileResult>;

export function RestoreProfileArchive(arg1:string):Promise<types.GenericResponse>;

export function SwapProfile(arg1:types.SwapProfileRequest):Promise<types.UserProfileResult>;

export function SyncSubscriptions(arg1:string,arg2:boolean,arg3:boolean):Promise<types.SyncSubscriptionsResult>;

export function UpdateSubscriptions(arg1:types.UpdateSubscriptionsRequest):Promise<types.UpdateSubscriptionsResult>;

export function UpdateSubscriptionsToLatest(arg1:types.UpdateSubscriptionsToLatestRequest):Promise<types.UpdateSubscriptionsResult>;

export function UpdateSystemPreferences(arg1:types.SystemPreferences):Promise<types.UserProfileResult>;

export function UpdateUIPreferences(arg1:types.UIPreferences):Promise<types.UserProfileResult>;
