// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddInstalledMap(arg1:string,arg2:string,arg3:types.ConfigData):Promise<void>;

export function AddInstalledMod(arg1:string,arg2:string):Promise<void>;

export function BootstrapInstalledStateFromProfile(arg1:types.UserProfile):Promise<void>;

export function GetAssetDownloadCounts(arg1:types.AssetType,arg2:string):Promise<types.AssetDownloadCountsResponse>;

export function GetDownloadCountsByAssetType(arg1:types.AssetType):Promise<types.DownloadCountsByAssetTypeResponse>;

export function GetGalleryImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetInstalledMapCodes():Promise<Array<string>>;

export function GetInstalledMaps():Promise<Array<types.InstalledMapInfo>>;

export function GetInstalledMods():Promise<Array<types.InstalledModInfo>>;

export function GetIntegrityReport(arg1:types.AssetType):Promise<types.RegistryIntegrityReport>;

export function GetMap(arg1:string):Promise<types.MapManifest>;

export function GetMaps():Promise<Array<types.MapManifest>>;

export function GetMod(arg1:string):Promise<types.ModManifest>;

export function GetMods():Promise<Array<types.ModManifest>>;

export function GetVersions(arg1:string,arg2:string):Promise<Array<types.VersionInfo>>;

export function Initialize():Promise<void>;

export function Refresh():Promise<void>;

export function RemoveInstalledMap(arg1:string):Promise<void>;

export function RemoveInstalledMod(arg1:string):Promise<void>;

export function SetInstalledMapsFromPath(arg1:string):Promise<void>;

export function SetInstalledModsFromPath(arg1:string):Promise<void>;

export function WriteInstalledToDisk():Promise<void>;
