// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVanillaMapCodes() {
  return window['go']['main']['App']['GetVanillaMapCodes']();
}

export function InstallMap(arg1, arg2) {
  return window['go']['main']['App']['InstallMap'](arg1, arg2);
}

export function InstallMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallMod'](arg1, arg2, arg3);
}
