// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deeplink} from '../models';
import {types} from '../models';

export function ConsumePendingDeepLink():Promise<Record<string, string>>;

export function GetCurrentVersion():Promise<string>;

export function GetGameVersion():Promise<string>;

export function GetPlatform():Promise<string>;

export function HandleDeepLinkTarget(arg1:deeplink.Target):Promise<void>;

export function HandleDeepLinkURL(arg1:string):Promise<void>;

export function InstallLinuxSandbox():Promise<void>;

export function IsGameRunning():Promise<boolean>;

export function IsStartupReady():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function ManuallyCheckForUpdates():Promise<void>;

export function OpenInFileExplorer(arg1:string):Promise<types.GenericResponse>;

export function SandboxIsInstalled():Promise<boolean>;

export function StopGame():Promise<void>;
