// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentVersion():Promise<string>;

export function GetGameVersion():Promise<string>;

export function IsGameRunning():Promise<boolean>;

export function IsStartupReady():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function ManuallyCheckForUpdates():Promise<void>;

export function StopGame():Promise<void>;
