// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsumePendingDeepLink() {
  return window['go']['main']['App']['ConsumePendingDeepLink']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetGameVersion() {
  return window['go']['main']['App']['GetGameVersion']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetTotalMemory() {
  return window['go']['main']['App']['GetTotalMemory']();
}

export function HandleDeepLinkTarget(arg1) {
  return window['go']['main']['App']['HandleDeepLinkTarget'](arg1);
}

export function HandleDeepLinkURL(arg1) {
  return window['go']['main']['App']['HandleDeepLinkURL'](arg1);
}

export function InstallLinuxSandbox() {
  return window['go']['main']['App']['InstallLinuxSandbox']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function IsStartupReady() {
  return window['go']['main']['App']['IsStartupReady']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function ManuallyCheckForUpdates() {
  return window['go']['main']['App']['ManuallyCheckForUpdates']();
}

export function OpenInFileExplorer(arg1) {
  return window['go']['main']['App']['OpenInFileExplorer'](arg1);
}

export function SandboxIsInstalled() {
  return window['go']['main']['App']['SandboxIsInstalled']();
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}
