// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['main']['Config']['ClearConfig']();
}

export function GetConfig() {
  return window['go']['main']['Config']['GetConfig']();
}

export function OpenExecutableDialog(arg1) {
  return window['go']['main']['Config']['OpenExecutableDialog'](arg1);
}

export function OpenMetroMakerDataFolderDialog(arg1) {
  return window['go']['main']['Config']['OpenMetroMakerDataFolderDialog'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['Config']['SaveConfig']();
}

export function SetConfig(arg1) {
  return window['go']['main']['Config']['SetConfig'](arg1);
}
