// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['main']['Config']['ClearConfig']();
}

export function ResolveConfig() {
  return window['go']['main']['Config']['ResolveConfig']();
}

export function SetConfig(arg1) {
  return window['go']['main']['Config']['SetConfig'](arg1);
}

export function UpdateExecutable(arg1) {
  return window['go']['main']['Config']['UpdateExecutable'](arg1);
}

export function UpdateMetroMakerDataFolder(arg1) {
  return window['go']['main']['Config']['UpdateMetroMakerDataFolder'](arg1);
}
