// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ResolveConfig():Promise<main.ResolveConfigResult>;

export function UpdateExecutable(arg1:string):Promise<main.AppConfig>;

export function UpdateModFolder(arg1:string):Promise<main.AppConfig>;
