// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ClearConfig():Promise<types.AppConfig>;

export function GetConfig():Promise<types.ResolveConfigResult>;

export function OpenExecutableDialog(arg1:types.SetConfigPathOptions):Promise<types.SetConfigPathResult>;

export function OpenMetroMakerDataFolderDialog(arg1:types.SetConfigPathOptions):Promise<types.SetConfigPathResult>;

export function SaveConfig():Promise<types.ResolveConfigResult>;

export function SetConfig(arg1:types.AppConfig):Promise<types.AppConfig>;
