// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearConfig():Promise<main.AppConfig>;

export function ResolveConfig():Promise<main.ResolveConfigResult>;

export function SetConfig(arg1:main.AppConfig):Promise<main.AppConfig>;

export function UpdateExecutable(arg1:string):Promise<main.AppConfig>;

export function UpdateMetroMakerDataFolder(arg1:string):Promise<main.AppConfig>;
