// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResolveConfig() {
  return window['go']['main']['Config']['ResolveConfig']();
}

export function UpdateExecutable(arg1) {
  return window['go']['main']['Config']['UpdateExecutable'](arg1);
}

export function UpdateModFolder(arg1) {
  return window['go']['main']['Config']['UpdateModFolder'](arg1);
}
