// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInstalledMap(arg1, arg2, arg3) {
  return window['go']['main']['Registry']['AddInstalledMap'](arg1, arg2, arg3);
}

export function AddInstalledMod(arg1, arg2) {
  return window['go']['main']['Registry']['AddInstalledMod'](arg1, arg2);
}

export function GetGalleryImage(arg1, arg2, arg3) {
  return window['go']['main']['Registry']['GetGalleryImage'](arg1, arg2, arg3);
}

export function GetInstalledMapCodes() {
  return window['go']['main']['Registry']['GetInstalledMapCodes']();
}

export function GetInstalledMaps() {
  return window['go']['main']['Registry']['GetInstalledMaps']();
}

export function GetInstalledMods() {
  return window['go']['main']['Registry']['GetInstalledMods']();
}

export function GetMap(arg1) {
  return window['go']['main']['Registry']['GetMap'](arg1);
}

export function GetMaps() {
  return window['go']['main']['Registry']['GetMaps']();
}

export function GetMod(arg1) {
  return window['go']['main']['Registry']['GetMod'](arg1);
}

export function GetMods() {
  return window['go']['main']['Registry']['GetMods']();
}

export function GetVersions(arg1, arg2) {
  return window['go']['main']['Registry']['GetVersions'](arg1, arg2);
}

export function Refresh() {
  return window['go']['main']['Registry']['Refresh']();
}

export function RemoveInstalledMap(arg1) {
  return window['go']['main']['Registry']['RemoveInstalledMap'](arg1);
}

export function RemoveInstalledMod(arg1) {
  return window['go']['main']['Registry']['RemoveInstalledMod'](arg1);
}

export function WriteInstalledToDisk() {
  return window['go']['main']['Registry']['WriteInstalledToDisk']();
}
