// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveProfile() {
  return window['go']['main']['UserProfiles']['GetActiveProfile']();
}

export function ResetUserProfiles() {
  return window['go']['main']['UserProfiles']['ResetUserProfiles']();
}

export function UpdateSubscriptions(arg1) {
  return window['go']['main']['UserProfiles']['UpdateSubscriptions'](arg1);
}
